export { default as Home } from './Home';
export { default as Products } from './Products';
// export { default as Product } from './Product';
export { default as AboutPage } from './AboutPage';
export { default as ContactPage } from './ContactPage';
export { default as Cart } from './Cart';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Billing } from './Billing';
export { default as PageNotFound } from './PageNotFound';
export { default as AddCategory } from './AddCategory';
export { default as AddProduct } from './AddProduct';
export { default as MyOrders } from './MyOrders';
export { default as OrdersPage } from './OrdersPage';
export { default as AllUsersPage } from './AllUsersPage';
